"""empty message

Revision ID: 21e0a3eeb941
Revises: a30a60af0bf5
Create Date: 2016-12-29 21:36:34.249484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21e0a3eeb941'
down_revision = 'a30a60af0bf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('file_type', sa.String(length=64), nullable=False),
    sa.Column('file_name', sa.String(length=64), nullable=True),
    sa.Column('content_logo', sa.String(length=64), nullable=True),
    sa.Column('content_title', sa.String(length=64), nullable=True),
    sa.Column('content_sub_title', sa.String(length=64), nullable=True),
    sa.Column('content_description', sa.String(length=64), nullable=True),
    sa.Column('design_background_image', sa.String(length=64), nullable=True),
    sa.Column('design_background_color', sa.String(length=64), nullable=True),
    sa.Column('design_background_repeat', sa.String(length=64), nullable=True),
    sa.Column('design_font_family', sa.String(length=64), nullable=True),
    sa.Column('design_base_font_size', sa.String(length=64), nullable=True),
    sa.Column('design_font_color', sa.String(length=64), nullable=True),
    sa.Column('design_content_alignment', sa.String(length=64), nullable=True),
    sa.Column('design_content_direction', sa.String(length=64), nullable=True),
    sa.Column('design_additional_styles', sa.String(length=64), nullable=True),
    sa.Column('search_results_title', sa.String(length=64), nullable=True),
    sa.Column('search_results_description', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pages_id'), 'pages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pages_id'), table_name='pages')
    op.drop_table('pages')
    # ### end Alembic commands ###
