"""empty message

Revision ID: 46f6f051f4db
Revises: None
Create Date: 2018-10-02 23:45:26.382572

"""

# revision identifiers, used by Alembic.
revision = '46f6f051f4db'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('site_name', sa.String(length=32), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('email_confirmed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_name')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('file_type', sa.String(length=16), nullable=False),
    sa.Column('file_name', sa.String(length=128), nullable=True),
    sa.Column('content_logo', sa.String(length=128), nullable=True),
    sa.Column('content_title', sa.Text(), nullable=True),
    sa.Column('content_sub_title', sa.Text(), nullable=True),
    sa.Column('content_description', sa.Text(), nullable=True),
    sa.Column('design_background_image', sa.String(length=128), nullable=True),
    sa.Column('design_background_color', sa.String(length=8), nullable=True),
    sa.Column('design_background_repeat', sa.String(length=16), nullable=True),
    sa.Column('design_font_family', sa.String(length=128), nullable=True),
    sa.Column('design_font_color', sa.String(length=8), nullable=True),
    sa.Column('design_content_alignment', sa.String(length=8), nullable=True),
    sa.Column('design_content_direction', sa.String(length=3), nullable=True),
    sa.Column('design_additional_styles', sa.Text(), nullable=True),
    sa.Column('search_results_title', sa.Text(), nullable=True),
    sa.Column('search_results_description', sa.Text(), nullable=True),
    sa.Column('google_analytics_code', sa.String(length=24), nullable=True),
    sa.Column('countdown_timezone', sa.String(length=64), nullable=True),
    sa.Column('countdown_datetime', sa.DateTime(), nullable=True),
    sa.Column('countdown_redirect_url', sa.String(length=128), nullable=True),
    sa.Column('mailing_list_service', sa.String(length=128), nullable=True),
    sa.Column('mailing_list_mailchimp_username', sa.String(length=128), nullable=True),
    sa.Column('mailing_list_mailchimp_api_key', sa.String(length=128), nullable=True),
    sa.Column('mailing_list_mailchimp_list_id', sa.String(length=128), nullable=True),
    sa.Column('mailing_list_successful_submission', sa.String(length=128), nullable=True),
    sa.Column('mailing_list_message', sa.String(length=128), nullable=True),
    sa.Column('mailing_list_redirect_url', sa.String(length=128), nullable=True),
    sa.Column('mailing_list_cta_color', sa.String(length=8), nullable=True),
    sa.Column('mailing_list_cta_text', sa.String(length=128), nullable=True),
    sa.Column('mailing_list_placeholder_text', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pages_id'), 'pages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pages_id'), table_name='pages')
    op.drop_table('pages')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
