"""empty message

Revision ID: 5e80497dda07
Revises: e237d38cdadd
Create Date: 2017-03-24 20:38:21.653735

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5e80497dda07'
down_revision = 'e237d38cdadd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pages', 'count_down_timezone', new_column_name='countdown_timezone', existing_type=sa.String(length=64))
    op.alter_column('pages', 'count_down_redirect_url', new_column_name='countdown_redirect_url', existing_type=sa.String(length=128))
    op.alter_column('pages', 'count_down_datetime', new_column_name='countdown_datetime', existing_type=sa.DateTime())

    # op.add_column('pages', sa.Column('countdown_timezone', sa.String(length=64), nullable=True))
    # op.add_column('pages', sa.Column('countdown_redirect_url', sa.String(length=128), nullable=True))
    # op.add_column('pages', sa.Column('countdown_datetime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pages', 'countdown_timezone', new_column_name='count_down_timezone', existing_type=sa.String(length=64))
    op.alter_column('pages', 'countdown_redirect_url', new_column_name='count_down_redirect_url', existing_type=sa.String(length=128))
    op.alter_column('pages', 'countdown_datetime', new_column_name='count_down_datetime', existing_type=sa.DateTime())
    # ### end Alembic commands ###
