"""empty message

Revision ID: 75486776dbcf
Revises: c3440fcf8a18
Create Date: 2017-01-16 14:27:37.577097

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '75486776dbcf'
down_revision = 'c3440fcf8a18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pages', 'updated_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('updated_at', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
