"""empty message

Revision ID: 98076db937fb
Revises: b0f2217d7010
Create Date: 2016-12-30 17:05:00.063980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98076db937fb'
down_revision = 'b0f2217d7010'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_site_name'), 'users', ['site_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_site_name'), table_name='users')
    # ### end Alembic commands ###
