"""empty message

Revision ID: 9bc61f6c1b3b
Revises: 10a1d0ee056a
Create Date: 2017-02-13 19:31:43.691568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bc61f6c1b3b'
down_revision = '10a1d0ee056a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('count_down_datetime', sa.DateTime(), nullable=True))
    op.add_column('pages', sa.Column('count_down_redirect_url', sa.String(length=128), nullable=True))
    op.add_column('pages', sa.Column('count_down_timezone', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pages', 'count_down_timezone')
    op.drop_column('pages', 'count_down_redirect_url')
    op.drop_column('pages', 'count_down_datetime')
    # ### end Alembic commands ###
