"""empty message

Revision ID: b0f2217d7010
Revises: 
Create Date: 2016-12-30 13:50:54.648224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0f2217d7010'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('file_type', sa.String(length=64), nullable=False),
    sa.Column('file_name', sa.String(length=64), nullable=True),
    sa.Column('content_logo', sa.String(length=64), nullable=True),
    sa.Column('content_title', sa.String(length=64), nullable=True),
    sa.Column('content_sub_title', sa.String(length=64), nullable=True),
    sa.Column('content_description', sa.String(length=64), nullable=True),
    sa.Column('design_background_image', sa.String(length=64), nullable=True),
    sa.Column('design_background_color', sa.String(length=64), nullable=True),
    sa.Column('design_background_repeat', sa.String(length=64), nullable=True),
    sa.Column('design_font_family', sa.String(length=64), nullable=True),
    sa.Column('design_base_font_size', sa.String(length=64), nullable=True),
    sa.Column('design_font_color', sa.String(length=64), nullable=True),
    sa.Column('design_content_alignment', sa.String(length=64), nullable=True),
    sa.Column('design_content_direction', sa.String(length=64), nullable=True),
    sa.Column('design_additional_styles', sa.String(length=64), nullable=True),
    sa.Column('search_results_title', sa.String(length=64), nullable=True),
    sa.Column('search_results_description', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pages_id'), 'pages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pages_id'), table_name='pages')
    op.drop_table('pages')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
