"""empty message

Revision ID: b756953d5736
Revises: c6b92c1dcff4
Create Date: 2018-12-24 22:37:18.293765

"""

# revision identifiers, used by Alembic.
revision = 'b756953d5736'
down_revision = 'c6b92c1dcff4'

from alembic import op
import sqlalchemy as sa
from pprint import pprint

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pages', 'file_type')
    op.alter_column('pages', 'file_name', new_column_name='name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pages', 'name', new_column_name='file_name')
    op.add_column('pages', sa.Column('file_type', sa.VARCHAR(length=16), autoincrement=False, nullable=False, server_default='welcome'))
    # ### end Alembic commands ###
