"""empty message

Revision ID: c3440fcf8a18
Revises: 1b59a63ccaa2
Create Date: 2017-01-16 14:25:39.490567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3440fcf8a18'
down_revision = '1b59a63ccaa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('google_analytics_code', sa.String(length=24), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pages', 'google_analytics_code')
    # ### end Alembic commands ###
