"""empty message

Revision ID: e237d38cdadd
Revises: 9bc61f6c1b3b
Create Date: 2017-02-27 20:05:50.251374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e237d38cdadd'
down_revision = '9bc61f6c1b3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('mailing_list_cta_color', sa.String(length=8), nullable=True))
    op.add_column('pages', sa.Column('mailing_list_cta_text', sa.String(length=128), nullable=True))
    op.add_column('pages', sa.Column('mailing_list_mailchimp_api_key', sa.String(length=128), nullable=True))
    op.add_column('pages', sa.Column('mailing_list_mailchimp_list_id', sa.String(length=128), nullable=True))
    op.add_column('pages', sa.Column('mailing_list_mailchimp_username', sa.String(length=128), nullable=True))
    op.add_column('pages', sa.Column('mailing_list_message', sa.String(length=128), nullable=True))
    op.add_column('pages', sa.Column('mailing_list_placeholder_text', sa.String(length=128), nullable=True))
    op.add_column('pages', sa.Column('mailing_list_redirect_url', sa.String(length=128), nullable=True))
    op.add_column('pages', sa.Column('mailing_list_service', sa.String(length=128), nullable=True))
    op.add_column('pages', sa.Column('mailing_list_successful_submission', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pages', 'mailing_list_successful_submission')
    op.drop_column('pages', 'mailing_list_service')
    op.drop_column('pages', 'mailing_list_redirect_url')
    op.drop_column('pages', 'mailing_list_placeholder_text')
    op.drop_column('pages', 'mailing_list_message')
    op.drop_column('pages', 'mailing_list_mailchimp_username')
    op.drop_column('pages', 'mailing_list_mailchimp_list_id')
    op.drop_column('pages', 'mailing_list_mailchimp_api_key')
    op.drop_column('pages', 'mailing_list_cta_text')
    op.drop_column('pages', 'mailing_list_cta_color')
    # ### end Alembic commands ###
