"""empty message

Revision ID: f9996189c292
Revises: 9bc61f6c1b3b
Create Date: 2017-02-21 17:19:20.316547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9996189c292'
down_revision = '9bc61f6c1b3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('mailing_list_completion_url', sa.String(length=128), nullable=True))
    op.add_column('pages', sa.Column('mailing_list_mailchimp_api_key', sa.String(length=128), nullable=True))
    op.add_column('pages', sa.Column('mailing_list_mailchimp_list_id', sa.String(length=128), nullable=True))
    op.add_column('pages', sa.Column('mailing_list_mailchimp_username', sa.String(length=128), nullable=True))
    op.add_column('pages', sa.Column('mailing_list_service', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pages', 'mailing_list_service')
    op.drop_column('pages', 'mailing_list_mailchimp_username')
    op.drop_column('pages', 'mailing_list_mailchimp_list_id')
    op.drop_column('pages', 'mailing_list_mailchimp_api_key')
    op.drop_column('pages', 'mailing_list_completion_url')
    # ### end Alembic commands ###
